//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnTongHop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichDay
    {
        public Nullable<int> tuanthu { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public int id_lopmonhoc { get; set; }
        public int id_cahoc { get; set; }
    
        public virtual CaHoc CaHoc { get; set; }
        public virtual LopMonHoc LopMonHoc { get; set; }
    }
}
